import { describe, expect, it } from "vitest";
import { validate, TYPES, MAX_SUBJECT_LENGTH, ALLOW_SCOPED_SUBJECTS } from "./index.js";

describe("validate-commit-msg", () => {
  describe("valid messages", () => {
    it("accepts a simple subject", () => {
      expect(validate("feat: add new thing")).toEqual([]);
    });

    it("accepts an unscoped subject with area in the description", () => {
      expect(validate("fix: handle parser edge case")).toEqual([]);
    });

    it("accepts an unscoped feat for registry work", () => {
      expect(validate("feat: add harness and verify skills")).toEqual([]);
    });

    it("accepts a breaking change with !", () => {
      expect(validate("refactor!: drop legacy api")).toEqual([]);
    });

    it("accepts a breaking change without scope", () => {
      expect(validate("feat!: require token")).toEqual([]);
    });

    it("accepts subject with a body", () => {
      const msg = "docs: update readme\n\nAdded section on testing.";
      expect(validate(msg)).toEqual([]);
    });

    it("accepts every allowed type", () => {
      for (const type of TYPES) {
        expect(validate(`${type}: something`)).toEqual([]);
      }
    });

    it("ignores comment lines", () => {
      const msg = "feat: add thing\n# This is a git comment\n";
      expect(validate(msg)).toEqual([]);
    });
  });

  describe("empty message", () => {
    it("rejects an empty string", () => {
      const v = validate("");
      expect(v).toHaveLength(1);
      expect(v[0]!.rule).toBe("empty");
    });

    it("rejects whitespace-only", () => {
      const v = validate("   \n  \n  ");
      expect(v).toHaveLength(1);
      expect(v[0]!.rule).toBe("empty");
    });

    it("rejects comment-only messages", () => {
      const v = validate("# This is a comment\n# Another comment");
      expect(v).toHaveLength(1);
      expect(v[0]!.rule).toBe("empty");
    });
  });

  describe("format violations", () => {
    it("rejects missing colon separator", () => {
      const v = validate("feat add thing");
      expect(v.some((x) => x.rule === "format")).toBe(true);
    });

    it("rejects uppercase type", () => {
      const v = validate("Feat: add thing");
      expect(v.some((x) => x.rule === "format")).toBe(true);
    });
  });

  describe("type violations", () => {
    it("rejects unknown type", () => {
      const v = validate("yolo: do stuff");
      expect(v.some((x) => x.rule === "type")).toBe(true);
    });
  });

  describe("scope violations", () => {
    it("rejects any parenthetical scope", () => {
      expect(validate("feat(registry): add harness skill").some((x) => x.rule === "scope")).toBe(
        true,
      );
      expect(validate("fix(parser): handle edge case").some((x) => x.rule === "scope")).toBe(true);
    });

    it("documents that scoped subjects are disabled", () => {
      expect(ALLOW_SCOPED_SUBJECTS).toBe(false);
    });
  });

  describe("length violations", () => {
    it("rejects a subject exceeding max length", () => {
      const long = "feat: " + "a".repeat(MAX_SUBJECT_LENGTH);
      const v = validate(long);
      expect(v.some((x) => x.rule === "length")).toBe(true);
    });

    it("accepts a subject at exactly max length", () => {
      const exact = "feat: " + "a".repeat(MAX_SUBJECT_LENGTH - 6);
      expect(exact.length).toBe(MAX_SUBJECT_LENGTH);
      expect(validate(exact)).toEqual([]);
    });
  });

  describe("casing violations", () => {
    it("rejects uppercase description start", () => {
      const v = validate("feat: Add new thing");
      expect(v.some((x) => x.rule === "lowercase")).toBe(true);
    });
  });

  describe("trailing period", () => {
    it("rejects description ending with a period", () => {
      const v = validate("fix: resolve the bug.");
      expect(v.some((x) => x.rule === "trailing-period")).toBe(true);
    });
  });

  describe("body separator", () => {
    it("rejects body without blank separator line", () => {
      const v = validate("feat: add thing\nBody without separator");
      expect(v.some((x) => x.rule === "body-separator")).toBe(true);
    });

    it("accepts body with proper blank separator line", () => {
      const msg = "feat: add thing\n\nBody with proper separator";
      expect(validate(msg)).toEqual([]);
    });
  });

  describe("forbidden patterns", () => {
    it("rejects AI co-author trailers", () => {
      const msg = "feat: add thing\n\nCo-authored-by: Cursor";
      const v = validate(msg);
      expect(v.some((x) => x.rule === "forbidden")).toBe(true);
    });

    it("rejects 'generated by' in body", () => {
      const msg = "feat: add thing\n\nGenerated by AI tool";
      const v = validate(msg);
      expect(v.some((x) => x.rule === "forbidden")).toBe(true);
    });

    it("rejects 'made with' in body", () => {
      const msg = "feat: add thing\n\nMade with love by AI";
      const v = validate(msg);
      expect(v.some((x) => x.rule === "forbidden")).toBe(true);
    });
  });

  describe("CRLF normalization", () => {
    it("handles Windows-style line endings", () => {
      const msg = "feat: add thing\r\n\r\nBody text here";
      expect(validate(msg)).toEqual([]);
    });
  });
});
