#!/usr/bin/env tsx

/**
 * Validates that a commit message follows Conventional Commits v1.0.0
 * and the project's additional conventions from commit-workflow/SKILL.md.
 *
 * Usage:
 *   - As a commit-msg hook: receives the commit message file path as $1
 *   - Standalone:           pass a file path or pipe a message via stdin
 *   - Agent invocation:     npx tsx .../index.ts --message "feat: add thing"
 *
 * Exit code 0 = valid, 1 = invalid.
 */

import { readFileSync } from "node:fs";

export const TYPES = new Set([
  "feat",
  "fix",
  "refactor",
  "perf",
  "test",
  "docs",
  "build",
  "chore",
  "style",
  "revert",
]);

export const MAX_SUBJECT_LENGTH = 72;

/** When false, subjects must be `type[!]: description` with no `(scope)` (see commit-workflow/SKILL.md). */
export const ALLOW_SCOPED_SUBJECTS = false;

export const FORBIDDEN_PATTERNS = [
  /made[- ]with[: ]/i,
  /generated by /i,
  /assisted by /i,
  /co-authored-by:\s*(cursor|claude|copilot|chatgpt|gpt|ai)/i,
];

export interface Violation {
  rule: string;
  detail: string;
}

function getCommitMessage(): string {
  const msgFlag = process.argv.indexOf("--message");
  if (msgFlag !== -1 && process.argv[msgFlag + 1]) {
    return process.argv[msgFlag + 1]!;
  }

  const filePath = process.argv[2];
  if (filePath) {
    return readFileSync(filePath, "utf-8");
  }

  console.error("check:commit-msg — no commit message provided");
  console.error("Usage: validate-commit-msg <file> | --message <string>");
  process.exit(1);
}

export function validate(raw: string): Violation[] {
  const violations: Violation[] = [];
  const lines = raw.replace(/\r\n/g, "\n").split("\n");

  const commentFiltered = lines.filter((l) => !l.startsWith("#"));
  if (commentFiltered.every((l) => l.trim() === "")) {
    violations.push({ rule: "empty", detail: "Commit message is empty" });
    return violations;
  }

  const subject = commentFiltered[0]?.trim() ?? "";

  const subjectPattern = /^([a-z]+)(?:\(([a-z0-9._-]+)\))?(!)?\s*:\s*(.+)$/;
  const match = subject.match(subjectPattern);

  if (!match) {
    violations.push({
      rule: "format",
      detail: `Subject does not match "type[!]: description" — got: "${subject}"`,
    });
    return violations;
  }

  const [, type, scope, , description] = match;

  if (scope && !ALLOW_SCOPED_SUBJECTS) {
    violations.push({
      rule: "scope",
      detail: `Do not use a parenthetical scope after the type — use "type: description" (e.g. "fix: handle parser edge case") and name areas in the body`,
    });
  }

  if (!TYPES.has(type!)) {
    violations.push({
      rule: "type",
      detail: `Unknown type "${type}" — allowed: ${[...TYPES].join(", ")}`,
    });
  }

  if (subject.length > MAX_SUBJECT_LENGTH) {
    violations.push({
      rule: "length",
      detail: `Subject is ${subject.length} chars (max ${MAX_SUBJECT_LENGTH})`,
    });
  }

  if (description && description !== description.trimStart()) {
    violations.push({
      rule: "leading-space",
      detail: "Description has leading whitespace after the colon",
    });
  }

  if (description && /^[A-Z]/.test(description)) {
    violations.push({
      rule: "lowercase",
      detail: "Description must start with a lowercase letter",
    });
  }

  if (description && description.endsWith(".")) {
    violations.push({
      rule: "trailing-period",
      detail: "Description must not end with a period",
    });
  }

  if (commentFiltered.length > 1 && commentFiltered[1]?.trim() !== "") {
    violations.push({
      rule: "body-separator",
      detail: "Body must be separated from subject by a blank line",
    });
  }

  const fullMessage = commentFiltered.join("\n");
  for (const pattern of FORBIDDEN_PATTERNS) {
    if (pattern.test(fullMessage)) {
      violations.push({
        rule: "forbidden",
        detail: `Message matches forbidden pattern: ${pattern}`,
      });
    }
  }

  return violations;
}

const isCLI = process.argv[1]?.includes("validate-commit-msg/hard/index.ts") ?? false;

if (isCLI) {
  const message = getCommitMessage();
  const violations = validate(message);

  if (violations.length === 0) {
    console.log("check:commit-msg — commit message is valid.");
    process.exit(0);
  } else {
    console.error(`check:commit-msg — found ${violations.length} violation(s):\n`);
    for (const v of violations) {
      console.error(`  [${v.rule}] ${v.detail}`);
    }
    console.error();
    process.exit(1);
  }
}
